name: GitHub activity data as a measure of developer activity

on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Random Commit Message
        id: random-message
        run: echo "RANDOM_MESSAGE=$(date +%s | sha256sum | base64 | head -c 32 ; echo)" >> $GITHUB_ENV

      - name: GitHub activity
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "${{ env.RANDOM_MESSAGE }}"
          git push
      - name: Release
        if: ${{ github.event.inputs.release != 'none' }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "**/*.txt"
          prerelease: ${{ github.event.inputs.release == 'pre-release' }}
          makeLatest: ${{ github.event.inputs.release == 'release' }}
          allowUpdates: "true"
          tag: version.txt
